### ISSUE TITLE
Xunit reporter outputs invalid XML

### ISSUE THREAD

**Issue by timbeadle** [adamstallard/grunt-vows-runner#1]
The Xunit reporter's XML output is invalid, and Jenkins doesn't work with it. It's the presence of a second `<testsuite>` element outside the root `<testsuite>` element.

``` xml
<testsuite name="api" timestamp="Tue, 19 Mar 2013 14:32:57 GMT">
  <testcase ... />
  <testcase ... />
  <testcase ... />
</testsuite>
<testsuite name="Results" tests="12" timestamp="Tue, 19 Mar 2013 14:32:57 GMT" errors="0" failures="0" skip="0" time="0.178" />
```

**Comment by adamstallard** [comment]
Thanks!  I took out the second testsuite element.  Hopefully Jenkins will know how to make the correct tallies without this information.  If not, I may have to buffer the entire output like the "xunit"  (lowercase x) reporter does.

Let me know if this upgrade helps, and if there are any other Jenkins bugs or feature requests.

**Comment by timbeadle** [comment]
Hi @adamstallard - that works a treat! Thanks for the super-fast turnaround :)
